name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile LLVM IR
      shell: bash
      run: |
        cd Swift-C++-IR-Comparison
        ./createIR.sh
    - name: Create Tar
      run: tar -cf llvm_ir.tar $(find . -name "*.ll")
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: llvm-ir
        path: llvm_ir.tar
