name: Swift

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"

jobs:
  ir:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v1
    - name: Compile Tool
      shell: bash
      run: |
        cd ComparisonTool
        swift build -c release
        cd ..

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.dockerlogin }}
    - name: Download Docker Image
      run: docker pull ghcr.io/secure-software-engineering/phasar:development
    - name: Run diff
      shell: bash
      run: |
        echo $(which docker)
        echo $(which swiftc)
        echo $(which clang++)
        ./ComparisonTool/.build/release/swift-llvm-statistics-comparison diff --config /home/runner/work/swift-llvm-statistics-comparison/swift-llvm-statistics-comparison/ComparisonTool/Sources/configs/comparison-github.json
    - name: Create Result Tar
      run: |
        cd /home/runner/work/swift-llvm-statistics-comparison
        tar -cf llvm_ir_statistics.tar results
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: llvm-ir-statistics
        path: llvm_ir_statistics.tar
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          llvm_ir_statistics.tar
