name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -c release
    - name: Compile LLVM IR
      shell: bash
      run: |
        cd Swift-C++-IR-Comparison
        ./createIR.sh
    - name: Upload LLVM IR
      uses: actions/upload-artifact@v3
      with:
        name: LLVM IR
        path: /**/*/*.ll
#     - name: Execute build
#       run: ./.build/release/swift-llvm-statistics-comparison
