name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ir:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile LLVM IR
      shell: bash
      run: |
        cd Swift-C++-IR-Comparison/scripts
        ./createIR.sh
        cd ..
    - name: Create IR Tar
      run: tar -cf llvm_ir.tar $(find . -name "*.ll")
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: llvm-ir
        path: llvm_ir.tar

  analysis:
    needs: ir
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.dockerlogin }}
      - name: Download Docker Image
        run: docker pull ghcr.io/secure-software-engineering/phasar:pr-524
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: llvm-ir
      - name: Extract IR
        run: tar -xvf llvm_ir.tar -C "Swift-C++-IR-Comparison"
      - name: Run Statistics Analysis
        run: |
          cd Swift-C++-IR-Comparison/scripts
          find .
          ./runDocker.sh
      - name: Create Statistics Tar
        run: |
          find .
          tar -cf llvm_ir_statistics.tar $(find . -name "psr-IrStatistics.json")
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: llvm-ir-statistics
          path: llvm_ir_statistics.tar

  differences:
    needs: analysis
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: llvm-ir-statistics
      - name: Extract Analysis Results
        run: |
         find .
         tar -xvf llvm_ir_statistics.tar -C "Swift-C++-IR-Comparison"
      - name: Build
        run: swift build -c release
      - name: Execute comparison
        run: |
          ./.build/release/swift-llvm-statistics-comparison --path $HOME
          find .
