name: Swift

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"

jobs:
  ir:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile LLVM IR
      shell: bash
      run: |
        cd Swift-C++-IR-Comparison/scripts
        ./createIR.sh
        cd ..
    - name: Create IR Tar
      run: tar -cf llvm_ir.tar $(find . -name "*.ll")
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: llvm-ir
        path: llvm_ir.tar
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.dockerlogin }}
    - name: Download Docker Image
      run: docker pull ghcr.io/secure-software-engineering/phasar:pr-524
    - name: Run Statistics Analysis
      run: |
        cd Swift-C++-IR-Comparison/scripts
        ./runDocker.sh
    - name: Create Statistics Tar
      run: |
        tar -cf llvm_ir_statistics.tar $(find . -name "psr-IrStatistics.json")
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: llvm-ir-statistics
        path: llvm_ir_statistics.tar
    - name: Build
      run: swift build -c release
    - name: Execute comparison
      run: |
        ./.build/release/swift-llvm-statistics-comparison --path $HOME
    - name: Create Comparison Tar
      run: |
        find .
        tar -cvf llvm_ir_statistics_comparison.tar $(find /Users/runner/diffs -name "*-comparison.json")
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: llvm-ir-statistics-comparison
        path: llvm_ir_statistics_comparison.tar
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: llvm-ir
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          llvm_ir_statistics_comparison.tar
          llvm_ir_statistics.tar
          llvm_ir.tar